# Generated by Django 6.0.1 on 2026-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INdexNumber', models.CharField(max_length=250)),
                ('FullNames', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('CurrentLocation', models.CharField(max_length=250)),
                ('HighestLevelofEducation', models.CharField(max_length=250)),
                ('DutyOfStation', models.CharField(max_length=250)),
                ('AvailabiltiyForRemotework', models.CharField(max_length=250)),
                ('Software_Expertise', models.CharField(max_length=250)),
                ('Software_Expertise_Level', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('Level_Of_responsibility', models.CharField(max_length=250)),
            ],
        ),
    ]
