# Generated by Django 6.0.1 on 2026-01-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='AvailabiltiyForRemotework',
            field=models.CharField(choices=[('Yes', 'yes'), ('NO', 'NO')], default='Yes', max_length=3),
        ),
    ]
