# Generated by Django 6.0.1 on 2026-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_staff_member_availabiltiyforremotework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='Software_Expertise_Level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advance', 'advance')], default='beginner', max_length=12),
        ),
    ]
