# Generated by Django 6.0.1 on 2026-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_staff_member_software_expertise_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='Level_Of_responsibility',
            field=models.CharField(choices=[('admin', 'admin'), ('staffmember', 'staffmember'), ('management', 'management')], default='staffmember', max_length=11),
        ),
    ]
