# Generated by Django 6.0.1 on 2026-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_staff_member_level_of_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='HighestLevelofEducation',
            field=models.CharField(choices=[('certificate', 'certificate'), ('diploma', 'diploma'), ('degree', 'degree'), ('master', 'master'), ('phd', 'phd')], default='degree', max_length=11),
        ),
    ]
